<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tableName = 'services';
        DB::table($tableName)->insert(
            array(
                [ 'id' => '1' , 'id_service_category' => '1' , 'description' => 'Kgs. LAVADO Y SECADO' , 'normal_price' => '16' ],
                [ 'id' => '2' , 'id_service_category' => '1' , 'description' => 'TOALLA LAVADO' , 'normal_price' => '29' ],
                [ 'id' => '3' , 'id_service_category' => '1' , 'description' => 'BOLSAS de plastico' , 'normal_price' => '5' ],
                [ 'id' => '4' , 'id_service_category' => '1' , 'description' => 'EDREDON DE PLUMAS TODO TAMAÑO' , 'normal_price' => '200' ],
                [ 'id' => '5' , 'id_service_category' => '1' , 'description' => 'Kgs. SECADO' , 'normal_price' => '15' ],
                [ 'id' => '6' , 'id_service_category' => '1' , 'description' => 'EDREDON/COBERTOR IND/MAT' , 'normal_price' => '65' ],
                [ 'id' => '7' , 'id_service_category' => '1' , 'description' => 'EDREDON/COBERTOR Q/K SIZE' , 'normal_price' => '95' ],
                [ 'id' => '8' , 'id_service_category' => '1' , 'description' => 'UNA CARGA DE CENTRIFUGADO' , 'normal_price' => '23' ],
                [ 'id' => '9' , 'id_service_category' => '1' , 'description' => 'LAVADO DE BLANCOS' , 'normal_price' => '18' ],
                [ 'id' => '10' , 'id_service_category' => '1' , 'description' => '3 KG LAVADO/SECADO' , 'normal_price' => '17.67' ],
                [ 'id' => '11' , 'id_service_category' => '1' , 'description' => 'SUAVIZANTE EXTRA' , 'normal_price' => '6' ],
                [ 'id' => '12' , 'id_service_category' => '1' , 'description' => 'VANISH' , 'normal_price' => '6' ],
                [ 'id' => '13' , 'id_service_category' => '1' , 'description' => 'GANCHOS' , 'normal_price' => '5' ],
                [ 'id' => '14' , 'id_service_category' => '2' , 'description' => 'Ajustar Blusa' , 'normal_price' => '55' ],
                [ 'id' => '15' , 'id_service_category' => '2' , 'description' => 'AJUSTE + PINZAS' , 'normal_price' => '100' ],
                [ 'id' => '16' , 'id_service_category' => '2' , 'description' => 'AJUSTE CAMISA' , 'normal_price' => '50' ],
                [ 'id' => '17' , 'id_service_category' => '2' , 'description' => 'AJUSTE COSTURA LATERALES' , 'normal_price' => '55' ],
                [ 'id' => '18' , 'id_service_category' => '2' , 'description' => 'AJUSTE DE FALDA ' , 'normal_price' => '60' ],
                [ 'id' => '19' , 'id_service_category' => '2' , 'description' => 'AJUSTE DE PANTALON' , 'normal_price' => '50' ],
                [ 'id' => '20' , 'id_service_category' => '2' , 'description' => 'AJUSTE DE VESTIDO SENCILLO' , 'normal_price' => '60' ],
                [ 'id' => '21' , 'id_service_category' => '2' , 'description' => 'AJUSTE SOLO PINZAS' , 'normal_price' => '50' ],
                [ 'id' => '22' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE CHAMARRA PLASTICO' , 'normal_price' => '80' ],
                [ 'id' => '23' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE CHAMARRA METALICO' , 'normal_price' => '100' ],
                [ 'id' => '24' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE INVISIBLE ' , 'normal_price' => '100' ],
                [ 'id' => '25' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE PANTALON MEZCLIL' , 'normal_price' => '50' ],
                [ 'id' => '26' , 'id_service_category' => '2' , 'description' => 'ABRIGO CORTO' , 'normal_price' => '33' ],
                [ 'id' => '27' , 'id_service_category' => '2' , 'description' => 'ABRIGO MEDIANO' , 'normal_price' => '33' ],
                [ 'id' => '28' , 'id_service_category' => '2' , 'description' => 'ABRIGO LARGO' , 'normal_price' => '39' ],
                [ 'id' => '29' , 'id_service_category' => '2' , 'description' => 'ABRIGO GRANDE Y GRUESO' , 'normal_price' => '39' ],
                [ 'id' => '30' , 'id_service_category' => '2' , 'description' => 'ABRIGO DE NIÑA ' , 'normal_price' => '33' ],
                [ 'id' => '31' , 'id_service_category' => '2' , 'description' => 'ABRIGO DE PLUMA ' , 'normal_price' => '33' ],
                [ 'id' => '32' , 'id_service_category' => '2' , 'description' => 'ABRIGO PIEL / GAMUZA' , 'normal_price' => '75' ],
                [ 'id' => '33' , 'id_service_category' => '2' , 'description' => 'ACCESORIOS EXTRAS  ' , 'normal_price' => '20' ],
                [ 'id' => '34' , 'id_service_category' => '2' , 'description' => 'CINTURON  ' , 'normal_price' => '20' ],
                [ 'id' => '35' , 'id_service_category' => '2' , 'description' => 'FAJILLA DE SMOKING ' , 'normal_price' => '20' ],
                [ 'id' => '36' , 'id_service_category' => '2' , 'description' => 'CINTILLAS  ' , 'normal_price' => '20' ],
                [ 'id' => '37' , 'id_service_category' => '2' , 'description' => 'CUELLO DESMONTABLE  ' , 'normal_price' => '20' ],
                [ 'id' => '38' , 'id_service_category' => '2' , 'description' => 'BOTONES  ' , 'normal_price' => '20' ],
                [ 'id' => '39' , 'id_service_category' => '2' , 'description' => 'MOÑOS  ' , 'normal_price' => '20' ],
                [ 'id' => '40' , 'id_service_category' => '2' , 'description' => 'ADORNOS  ' , 'normal_price' => '20' ],
                [ 'id' => '41' , 'id_service_category' => '2' , 'description' => 'GANCHOS ESPECIALES  ' , 'normal_price' => '20' ],
                [ 'id' => '42' , 'id_service_category' => '2' , 'description' => 'BATA SENCILLA' , 'normal_price' => '20' ],
                [ 'id' => '43' , 'id_service_category' => '2' , 'description' => 'BATA C/ALMIDON' , 'normal_price' => '21' ],
                [ 'id' => '44' , 'id_service_category' => '2' , 'description' => 'BATA DE DOCTOR ' , 'normal_price' => '20' ],
                [ 'id' => '45' , 'id_service_category' => '2' , 'description' => 'SABANA INDIVIDUAL  JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '46' , 'id_service_category' => '2' , 'description' => 'ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '47' , 'id_service_category' => '2' , 'description' => 'ALMOHADA PLUMA' , 'normal_price' => '1' ],
                [ 'id' => '48' , 'id_service_category' => '2' , 'description' => 'TEÑIDO JGO SABANAS IND/MAT ' , 'normal_price' => '0' ],
                [ 'id' => '49' , 'id_service_category' => '2' , 'description' => 'SABANA MATRIMONIAL , JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '50' , 'id_service_category' => '2' , 'description' => 'SABANA QUEEN SIZE, JUEGO 2PZAS' , 'normal_price' => '1' ],
                [ 'id' => '51' , 'id_service_category' => '2' , 'description' => 'SABANA KING SIZE, JUEGO JUEGO 2 PZAS' , 'normal_price' => '1' ],
                [ 'id' => '52' , 'id_service_category' => '2' , 'description' => 'TOALLA DE MANO' , 'normal_price' => '1' ],
                [ 'id' => '53' , 'id_service_category' => '2' , 'description' => 'TOALLA DE BAÑO' , 'normal_price' => '1' ],
                [ 'id' => '54' , 'id_service_category' => '2' , 'description' => 'TOALLA DE PLAYA' , 'normal_price' => '1' ],
                [ 'id' => '55' , 'id_service_category' => '2' , 'description' => 'FUNDA DE ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '56' , 'id_service_category' => '2' , 'description' => 'RODAPIÉ  ' , 'normal_price' => '1' ],
                [ 'id' => '57' , 'id_service_category' => '2' , 'description' => 'BERMUDA  ' , 'normal_price' => '20' ],
                [ 'id' => '58' , 'id_service_category' => '2' , 'description' => 'BERMUDA LINO / SEDA' , 'normal_price' => '20' ],
                [ 'id' => '59' , 'id_service_category' => '2' , 'description' => 'BLUSA SENCILLA  ' , 'normal_price' => '15' ],
                [ 'id' => '60' , 'id_service_category' => '2' , 'description' => 'BLUSA SEDA' , 'normal_price' => '30' ],
                [ 'id' => '61' , 'id_service_category' => '2' , 'description' => 'BLUSA LINO' , 'normal_price' => '30' ],
                [ 'id' => '62' , 'id_service_category' => '2' , 'description' => 'BLUSA TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '63' , 'id_service_category' => '2' , 'description' => 'CAMISA' , 'normal_price' => '16' ],
                [ 'id' => '64' , 'id_service_category' => '2' , 'description' => 'CAMISA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '65' , 'id_service_category' => '2' , 'description' => 'CAMISA ALMIDON' , 'normal_price' => '21' ],
                [ 'id' => '66' , 'id_service_category' => '2' , 'description' => 'CAMISA 1/2 DOCENA' , 'normal_price' => '75' ],
                [ 'id' => '67' , 'id_service_category' => '2' , 'description' => 'CAMISA DOCENA' , 'normal_price' => '150' ],
                [ 'id' => '68' , 'id_service_category' => '2' , 'description' => 'CAMISA 1/2 DOCENA ALMIDON' , 'normal_price' => '110' ],
                [ 'id' => '69' , 'id_service_category' => '2' , 'description' => 'CAMISA DOCENA ALMIDON' , 'normal_price' => '220' ],
                [ 'id' => '70' , 'id_service_category' => '2' , 'description' => 'CAMISA EXTRA X DOCENA' , 'normal_price' => '13' ],
                [ 'id' => '71' , 'id_service_category' => '2' , 'description' => 'CAMISA TEÑIDA' , 'normal_price' => '150' ],
                [ 'id' => '72' , 'id_service_category' => '2' , 'description' => 'COBERTOR INDIVIDUAL SENCILLO ' , 'normal_price' => '5' ],
                [ 'id' => '73' , 'id_service_category' => '2' , 'description' => 'COJIN CHICO  ' , 'normal_price' => '50' ],
                [ 'id' => '74' , 'id_service_category' => '2' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/FALDA' , 'normal_price' => '40' ],
                [ 'id' => '75' , 'id_service_category' => '2' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/PANTALON' , 'normal_price' => '40' ],
                [ 'id' => '76' , 'id_service_category' => '2' , 'description' => 'CONJUNTO SENCILLO 2PZ  CHALECO/PANTALON' , 'normal_price' => '40' ],
                [ 'id' => '77' , 'id_service_category' => '2' , 'description' => 'CONJUNTO DAMA 2 PZAS LINO/SEDA ' , 'normal_price' => '56' ],
                [ 'id' => '78' , 'id_service_category' => '2' , 'description' => 'CONJUNTO DAMA CON ADORNOS' , 'normal_price' => '56' ],
                [ 'id' => '79' , 'id_service_category' => '2' , 'description' => 'CONJUNTO 2PZ TABLEADO ' , 'normal_price' => '56' ],
                [ 'id' => '80' , 'id_service_category' => '2' , 'description' => 'CONJUNTO 3 PZAS ' , 'normal_price' => '56' ],
                [ 'id' => '81' , 'id_service_category' => '2' , 'description' => 'KG LAVADO MANTELERÍA' , 'normal_price' => '50' ],
                [ 'id' => '82' , 'id_service_category' => '2' , 'description' => 'CARPETA CHICA  ' , 'normal_price' => '1' ],
                [ 'id' => '83' , 'id_service_category' => '2' , 'description' => 'CHAMARRA ROMPEVIENTOS' , 'normal_price' => '40' ],
                [ 'id' => '84' , 'id_service_category' => '2' , 'description' => 'CHAMARRA LARGA PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '85' , 'id_service_category' => '2' , 'description' => 'CHAMARRA DE NIÑO ' , 'normal_price' => '40' ],
                [ 'id' => '86' , 'id_service_category' => '2' , 'description' => 'CHAMARRA PIEL/GAMUZA CORTA' , 'normal_price' => '75' ],
                [ 'id' => '87' , 'id_service_category' => '2' , 'description' => 'CHAMARRA PIEL/GAMUZA MEDIANA' , 'normal_price' => '75' ],
                [ 'id' => '88' , 'id_service_category' => '2' , 'description' => 'CHAMARRA PIEL/GAMUZA LARGA' , 'normal_price' => '75' ],
                [ 'id' => '89' , 'id_service_category' => '2' , 'description' => 'CHAMARRA TEÑIDA' , 'normal_price' => '150' ],
                [ 'id' => '90' , 'id_service_category' => '2' , 'description' => 'UNIVERSITARIA MANGAS PIEL' , 'normal_price' => '0' ],
                [ 'id' => '91' , 'id_service_category' => '2' , 'description' => 'CHAMARRA ROMPEVIENTOS 3/4' , 'normal_price' => '40' ],
                [ 'id' => '92' , 'id_service_category' => '2' , 'description' => 'CHAMARRA 2/V CORTA ' , 'normal_price' => '40' ],
                [ 'id' => '93' , 'id_service_category' => '2' , 'description' => 'CHAMARRA 2 VISTAS 3/4 ' , 'normal_price' => '40' ],
                [ 'id' => '94' , 'id_service_category' => '2' , 'description' => 'CHAMARRA 3/4 2 VISTAS O FORRADA  ' , 'normal_price' => '50' ],
                [ 'id' => '95' , 'id_service_category' => '2' , 'description' => 'CHAMARRA BORREGA 3/4  ' , 'normal_price' => '40' ],
                [ 'id' => '96' , 'id_service_category' => '2' , 'description' => 'CHAMARRA CORTA BORREGA ' , 'normal_price' => '40' ],
                [ 'id' => '97' , 'id_service_category' => '2' , 'description' => 'CHAMARRA CORTA PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '98' , 'id_service_category' => '2' , 'description' => 'CHAMARRA 3/4 PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '99' , 'id_service_category' => '2' , 'description' => 'CORT TAPICERIA LIENZO' , 'normal_price' => '50' ],
                [ 'id' => '100' , 'id_service_category' => '2' , 'description' => 'CORT, AHULADA LIENZO' , 'normal_price' => '50' ],
                [ 'id' => '101' , 'id_service_category' => '2' , 'description' => 'CORBATA  ' , 'normal_price' => '20' ],
                [ 'id' => '102' , 'id_service_category' => '2' , 'description' => 'CORBATA DE SEDA/LINO' , 'normal_price' => '20' ],
                [ 'id' => '103' , 'id_service_category' => '2' , 'description' => 'CHALECO SENCILLO  ' , 'normal_price' => '20' ],
                [ 'id' => '104' , 'id_service_category' => '2' , 'description' => 'CHALECO GRUESO' , 'normal_price' => '33' ],
                [ 'id' => '105' , 'id_service_category' => '2' , 'description' => 'CHALECO DE PLUMA ' , 'normal_price' => '33' ],
                [ 'id' => '106' , 'id_service_category' => '2' , 'description' => 'CHALECO TEÑIDO' , 'normal_price' => '0' ],
                [ 'id' => '107' , 'id_service_category' => '2' , 'description' => 'PANTS, JUEGO DE 2 PZAS ' , 'normal_price' => '39' ],
                [ 'id' => '108' , 'id_service_category' => '2' , 'description' => 'PLAYERAS DEPORTIVAS  ' , 'normal_price' => '20' ],
                [ 'id' => '109' , 'id_service_category' => '2' , 'description' => 'PANTS, 3 PIEZAS' , 'normal_price' => '40' ],
                [ 'id' => '110' , 'id_service_category' => '2' , 'description' => 'PAR DE TENIS' , 'normal_price' => '25' ],
                [ 'id' => '111' , 'id_service_category' => '2' , 'description' => 'EDREDÓN INDIVIDUAL  ' , 'normal_price' => '50' ],
                [ 'id' => '112' , 'id_service_category' => '2' , 'description' => 'EDREDÓN MATRIMONIAL  ' , 'normal_price' => '50' ],
                [ 'id' => '113' , 'id_service_category' => '2' , 'description' => 'EDREDÓN QUEEN SIZE ' , 'normal_price' => '60' ],
                [ 'id' => '114' , 'id_service_category' => '2' , 'description' => 'EDREDÓN KING SIZE ' , 'normal_price' => '60' ],
                [ 'id' => '115' , 'id_service_category' => '2' , 'description' => 'FALDA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '116' , 'id_service_category' => '2' , 'description' => 'FALDA RECTA LARGA ' , 'normal_price' => '20' ],
                [ 'id' => '117' , 'id_service_category' => '2' , 'description' => 'FALDA RECTA EXTRA LARGA' , 'normal_price' => '20' ],
                [ 'id' => '118' , 'id_service_category' => '2' , 'description' => 'FALDA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '119' , 'id_service_category' => '2' , 'description' => 'FALDA-PANTALON  ' , 'normal_price' => '20' ],
                [ 'id' => '120' , 'id_service_category' => '2' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM LARGA' , 'normal_price' => '33' ],
                [ 'id' => '121' , 'id_service_category' => '2' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM. ' , 'normal_price' => '33' ],
                [ 'id' => '122' , 'id_service_category' => '2' , 'description' => 'FALDA TABLEADA LINO/SEDA ' , 'normal_price' => '33' ],
                [ 'id' => '123' , 'id_service_category' => '2' , 'description' => 'FILIPINA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '124' , 'id_service_category' => '2' , 'description' => 'FILIPINA CON ALMIDÓN ' , 'normal_price' => '21' ],
                [ 'id' => '125' , 'id_service_category' => '2' , 'description' => 'GABARDINA NORMAL  ' , 'normal_price' => '33' ],
                [ 'id' => '126' , 'id_service_category' => '2' , 'description' => 'GABARDINA CON BORREGA ' , 'normal_price' => '56' ],
                [ 'id' => '127' , 'id_service_category' => '2' , 'description' => 'GABARDINA EXTRA LARGA ' , 'normal_price' => '56' ],
                [ 'id' => '128' , 'id_service_category' => '2' , 'description' => 'GUAYABERA  ' , 'normal_price' => '20' ],
                [ 'id' => '129' , 'id_service_category' => '2' , 'description' => 'FUNDAS DE SILLAS ' , 'normal_price' => '50' ],
                [ 'id' => '130' , 'id_service_category' => '2' , 'description' => 'MANTEL SENCILLO RECTANGULAR' , 'normal_price' => '0' ],
                [ 'id' => '131' , 'id_service_category' => '2' , 'description' => 'BUFANDA  ' , 'normal_price' => '20' ],
                [ 'id' => '132' , 'id_service_category' => '2' , 'description' => 'ROPÓN DE BAUTIZO ' , 'normal_price' => '56' ],
                [ 'id' => '133' , 'id_service_category' => '2' , 'description' => 'TENIS' , 'normal_price' => '0' ],
                [ 'id' => '134' , 'id_service_category' => '2' , 'description' => 'MALETAS LAVADO AL VAPOR' , 'normal_price' => '0' ],
                [ 'id' => '135' , 'id_service_category' => '2' , 'description' => 'ZALEA DE BORREGO' , 'normal_price' => '0' ],
                [ 'id' => '136' , 'id_service_category' => '2' , 'description' => 'MALETA DE MANO 30 X 50 CM' , 'normal_price' => '0' ],
                [ 'id' => '137' , 'id_service_category' => '2' , 'description' => 'TRAJE DE BAÑO' , 'normal_price' => '0' ],
                [ 'id' => '138' , 'id_service_category' => '2' , 'description' => 'FUNDA GRANDE COJIN' , 'normal_price' => '0' ],
                [ 'id' => '139' , 'id_service_category' => '2' , 'description' => 'TEÑIDO TAPETE BAÑO ' , 'normal_price' => '0' ],
                [ 'id' => '140' , 'id_service_category' => '2' , 'description' => 'TAPETE DE BAÑO CHICO' , 'normal_price' => '0' ],
                [ 'id' => '141' , 'id_service_category' => '2' , 'description' => 'FUNDA CHICA DE COJIN' , 'normal_price' => '0' ],
                [ 'id' => '142' , 'id_service_category' => '2' , 'description' => 'BANDERA  ' , 'normal_price' => '33' ],
                [ 'id' => '143' , 'id_service_category' => '2' , 'description' => 'CAPA SACERDOTAL SOTANA' , 'normal_price' => '0' ],
                [ 'id' => '144' , 'id_service_category' => '2' , 'description' => 'PERUANAS  ' , 'normal_price' => '33' ],
                [ 'id' => '145' , 'id_service_category' => '2' , 'description' => 'GORRA  ' , 'normal_price' => '20' ],
                [ 'id' => '146' , 'id_service_category' => '2' , 'description' => 'MASCADA' , 'normal_price' => '20' ],
                [ 'id' => '147' , 'id_service_category' => '2' , 'description' => 'MASCADA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '148' , 'id_service_category' => '2' , 'description' => 'OTROS' , 'normal_price' => '20' ],
                [ 'id' => '149' , 'id_service_category' => '2' , 'description' => 'CAPA  ' , 'normal_price' => '33' ],
                [ 'id' => '150' , 'id_service_category' => '2' , 'description' => 'PASHMINA' , 'normal_price' => '20' ],
                [ 'id' => '151' , 'id_service_category' => '2' , 'description' => 'OVEROL SENCILLO  ' , 'normal_price' => '40' ],
                [ 'id' => '152' , 'id_service_category' => '2' , 'description' => 'OVEROL DE NIÑO' , 'normal_price' => '40' ],
                [ 'id' => '153' , 'id_service_category' => '2' , 'description' => 'OVEROL DE TRABAJO/MECÁNICO' , 'normal_price' => '40' ],
                [ 'id' => '154' , 'id_service_category' => '2' , 'description' => 'PANTALÓN CABALLERO' , 'normal_price' => '25' ],
                [ 'id' => '155' , 'id_service_category' => '2' , 'description' => 'PANTALÓN DAMA' , 'normal_price' => '20' ],
                [ 'id' => '156' , 'id_service_category' => '2' , 'description' => 'PANTALÓN LINO/SEDA' , 'normal_price' => '30' ],
                [ 'id' => '157' , 'id_service_category' => '2' , 'description' => 'PANTALON TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '158' , 'id_service_category' => '2' , 'description' => 'MUÑECO DE PELUCHE CHICO' , 'normal_price' => '18' ],
                [ 'id' => '159' , 'id_service_category' => '2' , 'description' => 'MUÑECO DE PELUCHE MEDIANO' , 'normal_price' => '23' ],
                [ 'id' => '160' , 'id_service_category' => '2' , 'description' => 'MUÑECO DE PELUCHE GRANDE' , 'normal_price' => '28' ],
                [ 'id' => '161' , 'id_service_category' => '2' , 'description' => 'PLAYERA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '162' , 'id_service_category' => '2' , 'description' => 'PALATZO  ' , 'normal_price' => '30' ],
                [ 'id' => '163' , 'id_service_category' => '2' , 'description' => 'SACO CABALLERO' , 'normal_price' => '20' ],
                [ 'id' => '164' , 'id_service_category' => '2' , 'description' => 'SACO DAMA' , 'normal_price' => '20' ],
                [ 'id' => '165' , 'id_service_category' => '2' , 'description' => 'SACO DE LINO/SEDA ' , 'normal_price' => '20' ],
                [ 'id' => '166' , 'id_service_category' => '2' , 'description' => 'SACO CON ADORNOS ' , 'normal_price' => '33' ],
                [ 'id' => '167' , 'id_service_category' => '2' , 'description' => 'SACO DE NIÑO ' , 'normal_price' => '20' ],
                [ 'id' => '168' , 'id_service_category' => '2' , 'description' => 'SACO TEÑIDO' , 'normal_price' => '0' ],
                [ 'id' => '169' , 'id_service_category' => '2' , 'description' => 'SUDADERA  ' , 'normal_price' => '20' ],
                [ 'id' => '170' , 'id_service_category' => '2' , 'description' => 'TEÑIDO SUDADERA' , 'normal_price' => '0' ],
                [ 'id' => '171' , 'id_service_category' => '2' , 'description' => 'SWEATER SENCILLO  ' , 'normal_price' => '20' ],
                [ 'id' => '172' , 'id_service_category' => '2' , 'description' => 'SWEATER 3/4 DE LARGO' , 'normal_price' => '20' ],
                [ 'id' => '173' , 'id_service_category' => '2' , 'description' => 'SWEATER GRUESO' , 'normal_price' => '33' ],
                [ 'id' => '174' , 'id_service_category' => '2' , 'description' => 'SWEATER DE NIÑO' , 'normal_price' => '20' ],
                [ 'id' => '175' , 'id_service_category' => '2' , 'description' => 'SWEATER ANGORA' , 'normal_price' => '56' ],
                [ 'id' => '176' , 'id_service_category' => '2' , 'description' => 'SWEATER MANGAS DE PIEL/GAMUZA' , 'normal_price' => '56' ],
                [ 'id' => '177' , 'id_service_category' => '2' , 'description' => 'SWEATER FRENTE DE PIEL/GAMUZA' , 'normal_price' => '56' ],
                [ 'id' => '178' , 'id_service_category' => '2' , 'description' => 'TEÑIDO SWETER SENCILLO' , 'normal_price' => '0' ],
                [ 'id' => '179' , 'id_service_category' => '2' , 'description' => 'TRAJE 2 PIEZAS ' , 'normal_price' => '40' ],
                [ 'id' => '180' , 'id_service_category' => '2' , 'description' => 'TRAJE 2 PZAS LINO/SEDA' , 'normal_price' => '56' ],
                [ 'id' => '181' , 'id_service_category' => '2' , 'description' => 'TRAJE 3 PIEZAS ' , 'normal_price' => '56' ],
                [ 'id' => '182' , 'id_service_category' => '2' , 'description' => 'TRAJE 3PZ LINO/SEDA ' , 'normal_price' => '75' ],
                [ 'id' => '183' , 'id_service_category' => '2' , 'description' => 'TRAJE DE NIÑO 2 PZAS ' , 'normal_price' => '40' ],
                [ 'id' => '184' , 'id_service_category' => '2' , 'description' => 'TRAJE DE NIÑO 3 PZAS ' , 'normal_price' => '56' ],
                [ 'id' => '185' , 'id_service_category' => '2' , 'description' => 'SMOKING 2 PIEZAS ' , 'normal_price' => '40' ],
                [ 'id' => '186' , 'id_service_category' => '2' , 'description' => 'SMOKING 3 PIEZAS ' , 'normal_price' => '56' ],
                [ 'id' => '187' , 'id_service_category' => '2' , 'description' => 'VESTIDO SENCILLO  ' , 'normal_price' => '33' ],
                [ 'id' => '188' , 'id_service_category' => '2' , 'description' => 'VESTIDO XV AÑOS ' , 'normal_price' => '75' ],
                [ 'id' => '189' , 'id_service_category' => '2' , 'description' => 'VESTIDO XV AÑOS PEDRERIA' , 'normal_price' => '75' ],
                [ 'id' => '190' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE NOVIA ' , 'normal_price' => '75' ],
                [ 'id' => '191' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE NOVIA CON PEDRERIA ' , 'normal_price' => '100' ],
                [ 'id' => '192' , 'id_service_category' => '2' , 'description' => 'VESTIDO TEÑIDO' , 'normal_price' => '56' ],
                [ 'id' => '193' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE COKTAIL C/PEDRERIA' , 'normal_price' => '0' ],
                [ 'id' => '194' , 'id_service_category' => '2' , 'description' => 'VESTIDO EXTRA LARGO ' , 'normal_price' => '56' ],
                [ 'id' => '195' , 'id_service_category' => '2' , 'description' => 'VESTIDO LINO/SEDA  ' , 'normal_price' => '75' ],
                [ 'id' => '196' , 'id_service_category' => '2' , 'description' => 'VESTIDO LINO/SEDA EXT LARGO' , 'normal_price' => '75' ],
                [ 'id' => '197' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE NIÑA ' , 'normal_price' => '33' ],
                [ 'id' => '198' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE NIÑA FIESTA' , 'normal_price' => '56' ],
                [ 'id' => '199' , 'id_service_category' => '2' , 'description' => 'VESTIDO PRIMERA COMUNION' , 'normal_price' => '75' ],
                [ 'id' => '200' , 'id_service_category' => '2' , 'description' => 'VESTIDO DE COCKTAIL' , 'normal_price' => '33' ],
                [ 'id' => '201' , 'id_service_category' => '2' , 'description' => 'VESTIDO PEDR O ADORNOS' , 'normal_price' => '75' ],
                [ 'id' => '202' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE PANTALON VESTIR' , 'normal_price' => '55' ],
                [ 'id' => '203' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE PLASTIC/MOCHILA ' , 'normal_price' => '70' ],
                [ 'id' => '204' , 'id_service_category' => '2' , 'description' => 'CAMBIO D CARRO D CIERRE METAL' , 'normal_price' => '50' ],
                [ 'id' => '205' , 'id_service_category' => '2' , 'description' => 'CAMBIO DE BOTONES ' , 'normal_price' => '30' ],
                [ 'id' => '206' , 'id_service_category' => '2' , 'description' => 'CAMBIO CIERRE FALDA METALICO' , 'normal_price' => '50' ],
                [ 'id' => '207' , 'id_service_category' => '2' , 'description' => 'COSTURA HASTA 10 cms.' , 'normal_price' => '40' ],
                [ 'id' => '208' , 'id_service_category' => '2' , 'description' => 'DOBLADILLO PANTALON' , 'normal_price' => '65' ],
                [ 'id' => '209' , 'id_service_category' => '2' , 'description' => 'Dobladillo por M. Lineal' , 'normal_price' => '20' ],
                [ 'id' => '210' , 'id_service_category' => '2' , 'description' => 'DOBLADILLO VESTIDO SENCILLO' , 'normal_price' => '65' ],
                [ 'id' => '211' , 'id_service_category' => '2' , 'description' => 'DOBLADILLO VESTIDO SENCILLO CON FORRO' , 'normal_price' => '85' ],
                [ 'id' => '212' , 'id_service_category' => '2' , 'description' => 'DOBLADILLO VESTIDO CON FORRO DE NOCHE' , 'normal_price' => '200' ],
                [ 'id' => '213' , 'id_service_category' => '2' , 'description' => 'DOBLADILLO VESTIDO DE NOCHE' , 'normal_price' => '130' ],
                [ 'id' => '214' , 'id_service_category' => '2' , 'description' => 'Edredon Rep General' , 'normal_price' => '150' ],
                [ 'id' => '215' , 'id_service_category' => '2' , 'description' => 'Edredon Rep Mayor' , 'normal_price' => '80' ],
                [ 'id' => '216' , 'id_service_category' => '2' , 'description' => 'Edredon Rep Menor' , 'normal_price' => '60' ],
                [ 'id' => '217' , 'id_service_category' => '2' , 'description' => 'Parche para pantalon' , 'normal_price' => '60' ],
                [ 'id' => '218' , 'id_service_category' => '2' , 'description' => 'PONER UN BOTON' , 'normal_price' => '10' ],
                [ 'id' => '219' , 'id_service_category' => '2' , 'description' => 'REPARACIÓN MINIMA DE COSTURA' , 'normal_price' => '30' ],
                [ 'id' => '220' , 'id_service_category' => '2' , 'description' => 'REMACHE METALICO' , 'normal_price' => '50' ],
                [ 'id' => '221' , 'id_service_category' => '2' , 'description' => 'VALENCIANA' , 'normal_price' => '85' ],
                [ 'id' => '222' , 'id_service_category' => '2' , 'description' => 'VOLTEAR CUELLO DE CAMISAS' , 'normal_price' => '60' ],
                [ 'id' => '223' , 'id_service_category' => '3' , 'description' => 'ABRIGO CORTO' , 'normal_price' => '66' ],
                [ 'id' => '224' , 'id_service_category' => '3' , 'description' => 'ABRIGO MEDIANO' , 'normal_price' => '66' ],
                [ 'id' => '225' , 'id_service_category' => '3' , 'description' => 'ABRIGO LARGO' , 'normal_price' => '77' ],
                [ 'id' => '226' , 'id_service_category' => '3' , 'description' => 'ABRIGO GRANDE Y GRUESO' , 'normal_price' => '100' ],
                [ 'id' => '227' , 'id_service_category' => '3' , 'description' => 'ABRIGO DE NIÑA ' , 'normal_price' => '66' ],
                [ 'id' => '228' , 'id_service_category' => '3' , 'description' => 'ABRIGO DE PLUMA ' , 'normal_price' => '66' ],
                [ 'id' => '229' , 'id_service_category' => '3' , 'description' => 'ABRIGO PIEL / GAMUZA' , 'normal_price' => '260' ],
                [ 'id' => '230' , 'id_service_category' => '3' , 'description' => 'ACCESORIOS EXTRAS  ' , 'normal_price' => '40' ],
                [ 'id' => '231' , 'id_service_category' => '3' , 'description' => 'CINTURON  ' , 'normal_price' => '40' ],
                [ 'id' => '232' , 'id_service_category' => '3' , 'description' => 'FAJILLA DE SMOKING ' , 'normal_price' => '40' ],
                [ 'id' => '233' , 'id_service_category' => '3' , 'description' => 'CINTILLAS  ' , 'normal_price' => '40' ],
                [ 'id' => '234' , 'id_service_category' => '3' , 'description' => 'CUELLO DESMONTABLE  ' , 'normal_price' => '40' ],
                [ 'id' => '235' , 'id_service_category' => '3' , 'description' => 'BOTONES  ' , 'normal_price' => '40' ],
                [ 'id' => '236' , 'id_service_category' => '3' , 'description' => 'MOÑOS  ' , 'normal_price' => '40' ],
                [ 'id' => '237' , 'id_service_category' => '3' , 'description' => 'ADORNOS  ' , 'normal_price' => '40' ],
                [ 'id' => '238' , 'id_service_category' => '3' , 'description' => 'GANCHOS ESPECIALES  ' , 'normal_price' => '40' ],
                [ 'id' => '239' , 'id_service_category' => '3' , 'description' => 'BATA SENCILLA' , 'normal_price' => '40' ],
                [ 'id' => '240' , 'id_service_category' => '3' , 'description' => 'BATA C/ALMIDON' , 'normal_price' => '42' ],
                [ 'id' => '241' , 'id_service_category' => '3' , 'description' => 'BATA DE DOCTOR ' , 'normal_price' => '40' ],
                [ 'id' => '242' , 'id_service_category' => '3' , 'description' => 'SABANA INDIVIDUAL  JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '243' , 'id_service_category' => '3' , 'description' => 'ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '244' , 'id_service_category' => '3' , 'description' => 'ALMOHADA PLUMA' , 'normal_price' => '1' ],
                [ 'id' => '245' , 'id_service_category' => '3' , 'description' => 'TEÑIDO JGO SABANAS IND/MAT ' , 'normal_price' => '120' ],
                [ 'id' => '246' , 'id_service_category' => '3' , 'description' => 'SABANA MATRIMONIAL , JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '247' , 'id_service_category' => '3' , 'description' => 'SABANA QUEEN SIZE, JUEGO 2PZAS' , 'normal_price' => '1' ],
                [ 'id' => '248' , 'id_service_category' => '3' , 'description' => 'SABANA KING SIZE, JUEGO JUEGO 2 PZAS' , 'normal_price' => '1' ],
                [ 'id' => '249' , 'id_service_category' => '3' , 'description' => 'TOALLA DE MANO' , 'normal_price' => '1' ],
                [ 'id' => '250' , 'id_service_category' => '3' , 'description' => 'TOALLA DE BAÑO' , 'normal_price' => '1' ],
                [ 'id' => '251' , 'id_service_category' => '3' , 'description' => 'TOALLA DE PLAYA' , 'normal_price' => '1' ],
                [ 'id' => '252' , 'id_service_category' => '3' , 'description' => 'FUNDA DE ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '253' , 'id_service_category' => '3' , 'description' => 'RODAPIÉ  ' , 'normal_price' => '1' ],
                [ 'id' => '254' , 'id_service_category' => '3' , 'description' => 'BERMUDA  ' , 'normal_price' => '40' ],
                [ 'id' => '255' , 'id_service_category' => '3' , 'description' => 'BERMUDA LINO / SEDA' , 'normal_price' => '50' ],
                [ 'id' => '256' , 'id_service_category' => '3' , 'description' => 'BLUSA SENCILLA  ' , 'normal_price' => '40' ],
                [ 'id' => '257' , 'id_service_category' => '3' , 'description' => 'BLUSA SEDA' , 'normal_price' => '50' ],
                [ 'id' => '258' , 'id_service_category' => '3' , 'description' => 'BLUSA LINO' , 'normal_price' => '60' ],
                [ 'id' => '259' , 'id_service_category' => '3' , 'description' => 'BLUSA TEÑIDO' , 'normal_price' => '100' ],
                [ 'id' => '260' , 'id_service_category' => '3' , 'description' => 'CAMISA' , 'normal_price' => '40' ],
                [ 'id' => '261' , 'id_service_category' => '3' , 'description' => 'CAMISA LINO/SEDA' , 'normal_price' => '50' ],
                [ 'id' => '262' , 'id_service_category' => '3' , 'description' => 'CAMISA ALMIDON' , 'normal_price' => '45' ],
                [ 'id' => '263' , 'id_service_category' => '3' , 'description' => 'CAMISA 1/2 DOCENA' , 'normal_price' => '1' ],
                [ 'id' => '264' , 'id_service_category' => '3' , 'description' => 'CAMISA DOCENA' , 'normal_price' => '1' ],
                [ 'id' => '265' , 'id_service_category' => '3' , 'description' => 'CAMISA 1/2 DOCENA ALMIDON' , 'normal_price' => '1' ],
                [ 'id' => '266' , 'id_service_category' => '3' , 'description' => 'CAMISA DOCENA ALMIDON' , 'normal_price' => '1' ],
                [ 'id' => '267' , 'id_service_category' => '3' , 'description' => 'CAMISA EXTRA X DOCENA' , 'normal_price' => '1' ],
                [ 'id' => '268' , 'id_service_category' => '3' , 'description' => 'CAMISA TEÑIDA' , 'normal_price' => '80' ],
                [ 'id' => '269' , 'id_service_category' => '3' , 'description' => 'COBERTOR INDIVIDUAL SENCILLO ' , 'normal_price' => '100' ],
                [ 'id' => '270' , 'id_service_category' => '3' , 'description' => 'COJIN CHICO  ' , 'normal_price' => '25' ],
                [ 'id' => '271' , 'id_service_category' => '3' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/FALDA' , 'normal_price' => '80' ],
                [ 'id' => '272' , 'id_service_category' => '3' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/PANTALON' , 'normal_price' => '80' ],
                [ 'id' => '273' , 'id_service_category' => '3' , 'description' => 'CONJUNTO SENCILLO 2PZ  CHALECO/PANTALON' , 'normal_price' => '80' ],
                [ 'id' => '274' , 'id_service_category' => '3' , 'description' => 'CONJUNTO DAMA 2 PZAS LINO/SEDA ' , 'normal_price' => '111' ],
                [ 'id' => '275' , 'id_service_category' => '3' , 'description' => 'CONJUNTO DAMA CON ADORNOS' , 'normal_price' => '111' ],
                [ 'id' => '276' , 'id_service_category' => '3' , 'description' => 'CONJUNTO 2PZ TABLEADO ' , 'normal_price' => '111' ],
                [ 'id' => '277' , 'id_service_category' => '3' , 'description' => 'CONJUNTO 3 PZAS ' , 'normal_price' => '111' ],
                [ 'id' => '278' , 'id_service_category' => '3' , 'description' => 'KG LAVADO MANTELERÍA' , 'normal_price' => '100' ],
                [ 'id' => '279' , 'id_service_category' => '3' , 'description' => 'CARPETA CHICA / SERVILLETA' , 'normal_price' => '30' ],
                [ 'id' => '280' , 'id_service_category' => '3' , 'description' => 'CHAMARRA ROMPEVIENTOS' , 'normal_price' => '50' ],
                [ 'id' => '281' , 'id_service_category' => '3' , 'description' => 'CHAMARRA LARGA PLUMA ' , 'normal_price' => '77' ],
                [ 'id' => '282' , 'id_service_category' => '3' , 'description' => 'CHAMARRA DE NIÑO ' , 'normal_price' => '50' ],
                [ 'id' => '283' , 'id_service_category' => '3' , 'description' => 'CHAMARRA PIEL/GAMUZA CORTA' , 'normal_price' => '200' ],
                [ 'id' => '284' , 'id_service_category' => '3' , 'description' => 'CHAMARRA PIEL/GAMUZA MEDIANA' , 'normal_price' => '230' ],
                [ 'id' => '285' , 'id_service_category' => '3' , 'description' => 'CHAMARRA PIEL/GAMUZA LARGA' , 'normal_price' => '260' ],
                [ 'id' => '286' , 'id_service_category' => '3' , 'description' => 'CHAMARRA TEÑIDA' , 'normal_price' => '150' ],
                [ 'id' => '287' , 'id_service_category' => '3' , 'description' => 'UNIVERSITARIA MANGAS PIEL' , 'normal_price' => '180' ],
                [ 'id' => '288' , 'id_service_category' => '3' , 'description' => 'CHAMARRA ROMPEVIENTOS 3/4' , 'normal_price' => '66' ],
                [ 'id' => '289' , 'id_service_category' => '3' , 'description' => 'CHAMARRA 2/V CORTA ' , 'normal_price' => '50' ],
                [ 'id' => '290' , 'id_service_category' => '3' , 'description' => 'CHAMARRA 2 VISTAS 3/4 ' , 'normal_price' => '66' ],
                [ 'id' => '291' , 'id_service_category' => '3' , 'description' => 'CHAMARRA 3/4 2 VISTAS O FORRADA  ' , 'normal_price' => '66' ],
                [ 'id' => '292' , 'id_service_category' => '3' , 'description' => 'CHAMARRA BORREGA 3/4  ' , 'normal_price' => '66' ],
                [ 'id' => '293' , 'id_service_category' => '3' , 'description' => 'CHAMARRA CORTA BORREGA ' , 'normal_price' => '66' ],
                [ 'id' => '294' , 'id_service_category' => '3' , 'description' => 'CHAMARRA CORTA PLUMA ' , 'normal_price' => '77' ],
                [ 'id' => '295' , 'id_service_category' => '3' , 'description' => 'CHAMARRA 3/4 PLUMA ' , 'normal_price' => '77' ],
                [ 'id' => '296' , 'id_service_category' => '3' , 'description' => 'CORT TAPICERIA LIENZO' , 'normal_price' => '100' ],
                [ 'id' => '297' , 'id_service_category' => '3' , 'description' => 'CORT, AHULADA LIENZO' , 'normal_price' => '100' ],
                [ 'id' => '298' , 'id_service_category' => '3' , 'description' => 'CORBATA  ' , 'normal_price' => '30' ],
                [ 'id' => '299' , 'id_service_category' => '3' , 'description' => 'CORBATA DE SEDA/LINO' , 'normal_price' => '30' ],
                [ 'id' => '300' , 'id_service_category' => '3' , 'description' => 'CHALECO SENCILLO  ' , 'normal_price' => '40' ],
                [ 'id' => '301' , 'id_service_category' => '3' , 'description' => 'CHALECO GRUESO' , 'normal_price' => '66' ],
                [ 'id' => '302' , 'id_service_category' => '3' , 'description' => 'CHALECO DE PLUMA ' , 'normal_price' => '66' ],
                [ 'id' => '303' , 'id_service_category' => '3' , 'description' => 'CHALECO TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '304' , 'id_service_category' => '3' , 'description' => 'PANTS, JUEGO DE 2 PZAS ' , 'normal_price' => '77' ],
                [ 'id' => '305' , 'id_service_category' => '3' , 'description' => 'PLAYERAS DEPORTIVAS  ' , 'normal_price' => '40' ],
                [ 'id' => '306' , 'id_service_category' => '3' , 'description' => 'PANTS, 3 PIEZAS' , 'normal_price' => '80' ],
                [ 'id' => '307' , 'id_service_category' => '3' , 'description' => 'PAR DE TENIS' , 'normal_price' => '50' ],
                [ 'id' => '308' , 'id_service_category' => '3' , 'description' => 'EDREDÓN INDIVIDUAL  ' , 'normal_price' => '100' ],
                [ 'id' => '309' , 'id_service_category' => '3' , 'description' => 'EDREDÓN MATRIMONIAL  ' , 'normal_price' => '100' ],
                [ 'id' => '310' , 'id_service_category' => '3' , 'description' => 'EDREDÓN QUEEN SIZE ' , 'normal_price' => '120' ],
                [ 'id' => '311' , 'id_service_category' => '3' , 'description' => 'EDREDÓN KING SIZE ' , 'normal_price' => '120' ],
                [ 'id' => '312' , 'id_service_category' => '3' , 'description' => 'FALDA SENCILLA  ' , 'normal_price' => '40' ],
                [ 'id' => '313' , 'id_service_category' => '3' , 'description' => 'FALDA RECTA LARGA ' , 'normal_price' => '40' ],
                [ 'id' => '314' , 'id_service_category' => '3' , 'description' => 'FALDA RECTA EXTRA LARGA' , 'normal_price' => '50' ],
                [ 'id' => '315' , 'id_service_category' => '3' , 'description' => 'FALDA LINO/SEDA' , 'normal_price' => '50' ],
                [ 'id' => '316' , 'id_service_category' => '3' , 'description' => 'FALDA-PANTALON  ' , 'normal_price' => '40' ],
                [ 'id' => '317' , 'id_service_category' => '3' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM LARGA' , 'normal_price' => '66' ],
                [ 'id' => '318' , 'id_service_category' => '3' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM. ' , 'normal_price' => '66' ],
                [ 'id' => '319' , 'id_service_category' => '3' , 'description' => 'FALDA TABLEADA LINO/SEDA ' , 'normal_price' => '66' ],
                [ 'id' => '320' , 'id_service_category' => '3' , 'description' => 'FILIPINA SENCILLA  ' , 'normal_price' => '40' ],
                [ 'id' => '321' , 'id_service_category' => '3' , 'description' => 'FILIPINA CON ALMIDÓN ' , 'normal_price' => '45' ],
                [ 'id' => '322' , 'id_service_category' => '3' , 'description' => 'GABARDINA NORMAL  ' , 'normal_price' => '66' ],
                [ 'id' => '323' , 'id_service_category' => '3' , 'description' => 'GABARDINA CON BORREGA ' , 'normal_price' => '111' ],
                [ 'id' => '324' , 'id_service_category' => '3' , 'description' => 'GABARDINA EXTRA LARGA ' , 'normal_price' => '111' ],
                [ 'id' => '325' , 'id_service_category' => '3' , 'description' => 'GUAYABERA  ' , 'normal_price' => '40' ],
                [ 'id' => '326' , 'id_service_category' => '3' , 'description' => 'FUNDAS DE SILLAS ' , 'normal_price' => '40' ],
                [ 'id' => '327' , 'id_service_category' => '3' , 'description' => 'MANTEL SENCILLO RECTANGULAR' , 'normal_price' => '80' ],
                [ 'id' => '328' , 'id_service_category' => '3' , 'description' => 'BUFANDA  ' , 'normal_price' => '40' ],
                [ 'id' => '329' , 'id_service_category' => '3' , 'description' => 'ROPÓN DE BAUTIZO ' , 'normal_price' => '111' ],
                [ 'id' => '330' , 'id_service_category' => '3' , 'description' => 'TENIS' , 'normal_price' => '50' ],
                [ 'id' => '331' , 'id_service_category' => '3' , 'description' => 'MALETAS LAVADO AL VAPOR' , 'normal_price' => '120' ],
                [ 'id' => '332' , 'id_service_category' => '3' , 'description' => 'ZALEA DE BORREGO' , 'normal_price' => '240' ],
                [ 'id' => '333' , 'id_service_category' => '3' , 'description' => 'MALETA DE MANO 30 X 50 CM' , 'normal_price' => '70' ],
                [ 'id' => '334' , 'id_service_category' => '3' , 'description' => 'TRAJE DE BAÑO' , 'normal_price' => '50' ],
                [ 'id' => '335' , 'id_service_category' => '3' , 'description' => 'FUNDA GRANDE COJIN' , 'normal_price' => '50' ],
                [ 'id' => '336' , 'id_service_category' => '3' , 'description' => 'TEÑIDO TAPETE BAÑO ' , 'normal_price' => '150' ],
                [ 'id' => '337' , 'id_service_category' => '3' , 'description' => 'TAPETE DE BAÑO CHICO' , 'normal_price' => '50' ],
                [ 'id' => '338' , 'id_service_category' => '3' , 'description' => 'FUNDA CHICA DE COJIN' , 'normal_price' => '30' ],
                [ 'id' => '339' , 'id_service_category' => '3' , 'description' => 'BANDERA  ' , 'normal_price' => '66' ],
                [ 'id' => '340' , 'id_service_category' => '3' , 'description' => 'CAPA SACERDOTAL SOTANA' , 'normal_price' => '90' ],
                [ 'id' => '341' , 'id_service_category' => '3' , 'description' => 'PERUANAS  ' , 'normal_price' => '66' ],
                [ 'id' => '342' , 'id_service_category' => '3' , 'description' => 'GORRA  ' , 'normal_price' => '40' ],
                [ 'id' => '343' , 'id_service_category' => '3' , 'description' => 'MASCADA' , 'normal_price' => '40' ],
                [ 'id' => '344' , 'id_service_category' => '3' , 'description' => 'MASCADA LINO/SEDA' , 'normal_price' => '40' ],
                [ 'id' => '345' , 'id_service_category' => '3' , 'description' => 'OTROS' , 'normal_price' => '40' ],
                [ 'id' => '346' , 'id_service_category' => '3' , 'description' => 'CAPA/CHALINA' , 'normal_price' => '66' ],
                [ 'id' => '347' , 'id_service_category' => '3' , 'description' => 'PASHMINA' , 'normal_price' => '40' ],
                [ 'id' => '348' , 'id_service_category' => '3' , 'description' => 'OVEROL SENCILLO  ' , 'normal_price' => '80' ],
                [ 'id' => '349' , 'id_service_category' => '3' , 'description' => 'OVEROL DE NIÑO' , 'normal_price' => '80' ],
                [ 'id' => '350' , 'id_service_category' => '3' , 'description' => 'OVEROL DE TRABAJO/MECÁNICO' , 'normal_price' => '80' ],
                [ 'id' => '351' , 'id_service_category' => '3' , 'description' => 'PANTALÓN CABALLERO' , 'normal_price' => '40' ],
                [ 'id' => '352' , 'id_service_category' => '3' , 'description' => 'PANTALÓN DAMA' , 'normal_price' => '40' ],
                [ 'id' => '353' , 'id_service_category' => '3' , 'description' => 'PANTALÓN LINO/SEDA' , 'normal_price' => '45' ],
                [ 'id' => '354' , 'id_service_category' => '3' , 'description' => 'PANTALON TEÑIDO' , 'normal_price' => '80' ],
                [ 'id' => '355' , 'id_service_category' => '3' , 'description' => 'MUÑECO DE PELUCHE CHICO' , 'normal_price' => '45' ],
                [ 'id' => '356' , 'id_service_category' => '3' , 'description' => 'MUÑECO DE PELUCHE MEDIANO' , 'normal_price' => '55' ],
                [ 'id' => '357' , 'id_service_category' => '3' , 'description' => 'MUÑECO DE PELUCHE GRANDE' , 'normal_price' => '65' ],
                [ 'id' => '358' , 'id_service_category' => '3' , 'description' => 'PLAYERA SENCILLA  ' , 'normal_price' => '40' ],
                [ 'id' => '359' , 'id_service_category' => '3' , 'description' => 'PALATZO  ' , 'normal_price' => '80' ],
                [ 'id' => '360' , 'id_service_category' => '3' , 'description' => 'SACO CABALLERO' , 'normal_price' => '40' ],
                [ 'id' => '361' , 'id_service_category' => '3' , 'description' => 'SACO DAMA' , 'normal_price' => '40' ],
                [ 'id' => '362' , 'id_service_category' => '3' , 'description' => 'SACO DE LINO/SEDA ' , 'normal_price' => '40' ],
                [ 'id' => '363' , 'id_service_category' => '3' , 'description' => 'SACO CON ADORNOS ' , 'normal_price' => '66' ],
                [ 'id' => '364' , 'id_service_category' => '3' , 'description' => 'SACO DE NIÑO ' , 'normal_price' => '40' ],
                [ 'id' => '365' , 'id_service_category' => '3' , 'description' => 'SACO TEÑIDO' , 'normal_price' => '0' ],
                [ 'id' => '366' , 'id_service_category' => '3' , 'description' => 'SUDADERA  ' , 'normal_price' => '40' ],
                [ 'id' => '367' , 'id_service_category' => '3' , 'description' => 'TEÑIDO SUDADERA' , 'normal_price' => '100' ],
                [ 'id' => '368' , 'id_service_category' => '3' , 'description' => 'SWEATER SENCILLO  ' , 'normal_price' => '40' ],
                [ 'id' => '369' , 'id_service_category' => '3' , 'description' => 'SWEATER 3/4 DE LARGO' , 'normal_price' => '40' ],
                [ 'id' => '370' , 'id_service_category' => '3' , 'description' => 'SWEATER GRUESO' , 'normal_price' => '66' ],
                [ 'id' => '371' , 'id_service_category' => '3' , 'description' => 'SWEATER DE NIÑO' , 'normal_price' => '40' ],
                [ 'id' => '372' , 'id_service_category' => '3' , 'description' => 'SWEATER ANGORA' , 'normal_price' => '111' ],
                [ 'id' => '373' , 'id_service_category' => '3' , 'description' => 'SWEATER MANGAS DE PIEL/GAMUZA' , 'normal_price' => '111' ],
                [ 'id' => '374' , 'id_service_category' => '3' , 'description' => 'SWEATER FRENTE DE PIEL/GAMUZA' , 'normal_price' => '111' ],
                [ 'id' => '375' , 'id_service_category' => '3' , 'description' => 'TEÑIDO SWETER SENCILLO' , 'normal_price' => '80' ],
                [ 'id' => '376' , 'id_service_category' => '3' , 'description' => 'TRAJE 2 PIEZAS ' , 'normal_price' => '80' ],
                [ 'id' => '377' , 'id_service_category' => '3' , 'description' => 'TRAJE 2 PZAS LINO/SEDA' , 'normal_price' => '111' ],
                [ 'id' => '378' , 'id_service_category' => '3' , 'description' => 'TRAJE 3 PIEZAS ' , 'normal_price' => '111' ],
                [ 'id' => '379' , 'id_service_category' => '3' , 'description' => 'TRAJE 3PZ LINO/SEDA ' , 'normal_price' => '150' ],
                [ 'id' => '380' , 'id_service_category' => '3' , 'description' => 'TRAJE DE NIÑO 2 PZAS ' , 'normal_price' => '80' ],
                [ 'id' => '381' , 'id_service_category' => '3' , 'description' => 'TRAJE DE NIÑO 3 PZAS ' , 'normal_price' => '111' ],
                [ 'id' => '382' , 'id_service_category' => '3' , 'description' => 'SMOKING 2 PIEZAS ' , 'normal_price' => '80' ],
                [ 'id' => '383' , 'id_service_category' => '3' , 'description' => 'SMOKING 3 PIEZAS ' , 'normal_price' => '111' ],
                [ 'id' => '384' , 'id_service_category' => '3' , 'description' => 'VESTIDO SENCILLO  ' , 'normal_price' => '66' ],
                [ 'id' => '385' , 'id_service_category' => '3' , 'description' => 'VESTIDO XV AÑOS ' , 'normal_price' => '200' ],
                [ 'id' => '386' , 'id_service_category' => '3' , 'description' => 'VESTIDO XV AÑOS PEDRERIA' , 'normal_price' => '250' ],
                [ 'id' => '387' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE NOVIA ' , 'normal_price' => '200' ],
                [ 'id' => '388' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE NOVIA CON PEDRERIA ' , 'normal_price' => '250' ],
                [ 'id' => '389' , 'id_service_category' => '3' , 'description' => 'VESTIDO TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '390' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE COKTAIL C/PEDRERIA' , 'normal_price' => '100' ],
                [ 'id' => '391' , 'id_service_category' => '3' , 'description' => 'VESTIDO EXTRA LARGO ' , 'normal_price' => '90' ],
                [ 'id' => '392' , 'id_service_category' => '3' , 'description' => 'VESTIDO LINO/SEDA  ' , 'normal_price' => '130' ],
                [ 'id' => '393' , 'id_service_category' => '3' , 'description' => 'VESTIDO LINO/SEDA EXT LARGO' , 'normal_price' => '150' ],
                [ 'id' => '394' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE NIÑA ' , 'normal_price' => '66' ],
                [ 'id' => '395' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE NIÑA FIESTA' , 'normal_price' => '100' ],
                [ 'id' => '396' , 'id_service_category' => '3' , 'description' => 'VESTIDO PRIMERA COMUNION' , 'normal_price' => '150' ],
                [ 'id' => '397' , 'id_service_category' => '3' , 'description' => 'VESTIDO DE COCKTAIL' , 'normal_price' => '66' ],
                [ 'id' => '398' , 'id_service_category' => '3' , 'description' => 'VESTIDO PEDR O ADORNOS' , 'normal_price' => '150' ],
                [ 'id' => '399' , 'id_service_category' => '3' , 'description' => 'BANDERA CHICA' , 'normal_price' => '45' ],
                [ 'id' => '400' , 'id_service_category' => '3' , 'description' => 'CORTINA LARGA' , 'normal_price' => '90' ],
                [ 'id' => '401' , 'id_service_category' => '3' , 'description' => 'CORTINA DE BALCON' , 'normal_price' => '60' ],
                [ 'id' => '402' , 'id_service_category' => '3' , 'description' => 'CAMINO DE MESA EXLA' , 'normal_price' => '147' ],
                [ 'id' => '403' , 'id_service_category' => '3' , 'description' => 'DUVET' , 'normal_price' => '80' ],
                [ 'id' => '404' , 'id_service_category' => '4' , 'description' => 'ABRIGO CORTO' , 'normal_price' => '33' ],
                [ 'id' => '405' , 'id_service_category' => '4' , 'description' => 'ABRIGO MEDIANO' , 'normal_price' => '33' ],
                [ 'id' => '406' , 'id_service_category' => '4' , 'description' => 'ABRIGO LARGO' , 'normal_price' => '39' ],
                [ 'id' => '407' , 'id_service_category' => '4' , 'description' => 'ABRIGO GRANDE Y GRUESO' , 'normal_price' => '39' ],
                [ 'id' => '408' , 'id_service_category' => '4' , 'description' => 'ABRIGO DE NIÑA ' , 'normal_price' => '33' ],
                [ 'id' => '409' , 'id_service_category' => '4' , 'description' => 'ABRIGO DE PLUMA ' , 'normal_price' => '33' ],
                [ 'id' => '410' , 'id_service_category' => '4' , 'description' => 'ABRIGO PIEL / GAMUZA' , 'normal_price' => '75' ],
                [ 'id' => '411' , 'id_service_category' => '4' , 'description' => 'ACCESORIOS EXTRAS  ' , 'normal_price' => '20' ],
                [ 'id' => '412' , 'id_service_category' => '4' , 'description' => 'CINTURON  ' , 'normal_price' => '20' ],
                [ 'id' => '413' , 'id_service_category' => '4' , 'description' => 'FAJILLA DE SMOKING ' , 'normal_price' => '20' ],
                [ 'id' => '414' , 'id_service_category' => '4' , 'description' => 'CINTILLAS  ' , 'normal_price' => '20' ],
                [ 'id' => '415' , 'id_service_category' => '4' , 'description' => 'CUELLO DESMONTABLE  ' , 'normal_price' => '20' ],
                [ 'id' => '416' , 'id_service_category' => '4' , 'description' => 'BOTONES  ' , 'normal_price' => '20' ],
                [ 'id' => '417' , 'id_service_category' => '4' , 'description' => 'MOÑOS  ' , 'normal_price' => '20' ],
                [ 'id' => '418' , 'id_service_category' => '4' , 'description' => 'ADORNOS  ' , 'normal_price' => '20' ],
                [ 'id' => '419' , 'id_service_category' => '4' , 'description' => 'GANCHOS ESPECIALES  ' , 'normal_price' => '20' ],
                [ 'id' => '420' , 'id_service_category' => '4' , 'description' => 'BATA SENCILLA' , 'normal_price' => '20' ],
                [ 'id' => '421' , 'id_service_category' => '4' , 'description' => 'BATA C/ALMIDON' , 'normal_price' => '21' ],
                [ 'id' => '422' , 'id_service_category' => '4' , 'description' => 'BATA DE DOCTOR ' , 'normal_price' => '20' ],
                [ 'id' => '423' , 'id_service_category' => '4' , 'description' => 'SABANA INDIVIDUAL  JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '424' , 'id_service_category' => '4' , 'description' => 'ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '425' , 'id_service_category' => '4' , 'description' => 'ALMOHADA PLUMA' , 'normal_price' => '1' ],
                [ 'id' => '426' , 'id_service_category' => '4' , 'description' => 'TEÑIDO JGO SABANAS IND/MAT ' , 'normal_price' => '0' ],
                [ 'id' => '427' , 'id_service_category' => '4' , 'description' => 'SABANA MATRIMONIAL , JUEGO' , 'normal_price' => '1' ],
                [ 'id' => '428' , 'id_service_category' => '4' , 'description' => 'SABANA QUEEN SIZE, JUEGO 2PZAS' , 'normal_price' => '1' ],
                [ 'id' => '429' , 'id_service_category' => '4' , 'description' => 'SABANA KING SIZE, JUEGO JUEGO 2 PZAS' , 'normal_price' => '1' ],
                [ 'id' => '430' , 'id_service_category' => '4' , 'description' => 'TOALLA DE MANO' , 'normal_price' => '1' ],
                [ 'id' => '431' , 'id_service_category' => '4' , 'description' => 'TOALLA DE BAÑO' , 'normal_price' => '1' ],
                [ 'id' => '432' , 'id_service_category' => '4' , 'description' => 'TOALLA DE PLAYA' , 'normal_price' => '1' ],
                [ 'id' => '433' , 'id_service_category' => '4' , 'description' => 'FUNDA DE ALMOHADA' , 'normal_price' => '1' ],
                [ 'id' => '434' , 'id_service_category' => '4' , 'description' => 'RODAPIÉ  ' , 'normal_price' => '1' ],
                [ 'id' => '435' , 'id_service_category' => '4' , 'description' => 'BERMUDA  ' , 'normal_price' => '20' ],
                [ 'id' => '436' , 'id_service_category' => '4' , 'description' => 'BERMUDA LINO / SEDA' , 'normal_price' => '20' ],
                [ 'id' => '437' , 'id_service_category' => '4' , 'description' => 'BLUSA SENCILLA  ' , 'normal_price' => '15' ],
                [ 'id' => '438' , 'id_service_category' => '4' , 'description' => 'BLUSA SEDA' , 'normal_price' => '30' ],
                [ 'id' => '439' , 'id_service_category' => '4' , 'description' => 'BLUSA LINO' , 'normal_price' => '30' ],
                [ 'id' => '440' , 'id_service_category' => '4' , 'description' => 'BLUSA TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '441' , 'id_service_category' => '4' , 'description' => 'CAMISA' , 'normal_price' => '16' ],
                [ 'id' => '442' , 'id_service_category' => '4' , 'description' => 'CAMISA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '443' , 'id_service_category' => '4' , 'description' => 'CAMISA ALMIDON' , 'normal_price' => '21' ],
                [ 'id' => '444' , 'id_service_category' => '4' , 'description' => 'CAMISA 1/2 DOCENA' , 'normal_price' => '75' ],
                [ 'id' => '445' , 'id_service_category' => '4' , 'description' => 'CAMISA DOCENA' , 'normal_price' => '150' ],
                [ 'id' => '446' , 'id_service_category' => '4' , 'description' => 'CAMISA 1/2 DOCENA ALMIDON' , 'normal_price' => '110' ],
                [ 'id' => '447' , 'id_service_category' => '4' , 'description' => 'CAMISA DOCENA ALMIDON' , 'normal_price' => '220' ],
                [ 'id' => '448' , 'id_service_category' => '4' , 'description' => 'CAMISA EXTRA X DOCENA' , 'normal_price' => '13' ],
                [ 'id' => '449' , 'id_service_category' => '4' , 'description' => 'CAMISA TEÑIDA' , 'normal_price' => '150' ],
                [ 'id' => '450' , 'id_service_category' => '4' , 'description' => 'COBERTOR INDIVIDUAL SENCILLO ' , 'normal_price' => '5' ],
                [ 'id' => '451' , 'id_service_category' => '4' , 'description' => 'COJIN CHICO  ' , 'normal_price' => '50' ],
                [ 'id' => '452' , 'id_service_category' => '4' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/FALDA' , 'normal_price' => '40' ],
                [ 'id' => '453' , 'id_service_category' => '4' , 'description' => 'CONJUNTO SENCILLO 2PZ  SACO/PANTALON' , 'normal_price' => '40' ],
                [ 'id' => '454' , 'id_service_category' => '4' , 'description' => 'CONJUNTO SENCILLO 2PZ  CHALECO/PANTALON' , 'normal_price' => '40' ],
                [ 'id' => '455' , 'id_service_category' => '4' , 'description' => 'CONJUNTO DAMA 2 PZAS LINO/SEDA ' , 'normal_price' => '56' ],
                [ 'id' => '456' , 'id_service_category' => '4' , 'description' => 'CONJUNTO DAMA CON ADORNOS' , 'normal_price' => '56' ],
                [ 'id' => '457' , 'id_service_category' => '4' , 'description' => 'CONJUNTO 2PZ TABLEADO ' , 'normal_price' => '56' ],
                [ 'id' => '458' , 'id_service_category' => '4' , 'description' => 'CONJUNTO 3 PZAS ' , 'normal_price' => '56' ],
                [ 'id' => '459' , 'id_service_category' => '4' , 'description' => 'KG LAVADO MANTELERÍA' , 'normal_price' => '50' ],
                [ 'id' => '460' , 'id_service_category' => '4' , 'description' => 'CARPETA CHICA  / SERVILLETA' , 'normal_price' => '1' ],
                [ 'id' => '461' , 'id_service_category' => '4' , 'description' => 'CHAMARRA ROMPEVIENTOS' , 'normal_price' => '40' ],
                [ 'id' => '462' , 'id_service_category' => '4' , 'description' => 'CHAMARRA LARGA PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '463' , 'id_service_category' => '4' , 'description' => 'CHAMARRA DE NIÑO ' , 'normal_price' => '40' ],
                [ 'id' => '464' , 'id_service_category' => '4' , 'description' => 'CHAMARRA PIEL/GAMUZA CORTA' , 'normal_price' => '75' ],
                [ 'id' => '465' , 'id_service_category' => '4' , 'description' => 'CHAMARRA PIEL/GAMUZA MEDIANA' , 'normal_price' => '75' ],
                [ 'id' => '466' , 'id_service_category' => '4' , 'description' => 'CHAMARRA PIEL/GAMUZA LARGA' , 'normal_price' => '75' ],
                [ 'id' => '467' , 'id_service_category' => '4' , 'description' => 'CHAMARRA TEÑIDA' , 'normal_price' => '150' ],
                [ 'id' => '468' , 'id_service_category' => '4' , 'description' => 'UNIVERSITARIA MANGAS PIEL' , 'normal_price' => '0' ],
                [ 'id' => '469' , 'id_service_category' => '4' , 'description' => 'CHAMARRA ROMPEVIENTOS 3/4' , 'normal_price' => '40' ],
                [ 'id' => '470' , 'id_service_category' => '4' , 'description' => 'CHAMARRA 2/V CORTA ' , 'normal_price' => '40' ],
                [ 'id' => '471' , 'id_service_category' => '4' , 'description' => 'CHAMARRA 2 VISTAS 3/4 ' , 'normal_price' => '40' ],
                [ 'id' => '472' , 'id_service_category' => '4' , 'description' => 'CHAMARRA 3/4 2 VISTAS O FORRADA  ' , 'normal_price' => '50' ],
                [ 'id' => '473' , 'id_service_category' => '4' , 'description' => 'CHAMARRA BORREGA 3/4  ' , 'normal_price' => '40' ],
                [ 'id' => '474' , 'id_service_category' => '4' , 'description' => 'CHAMARRA CORTA BORREGA ' , 'normal_price' => '40' ],
                [ 'id' => '475' , 'id_service_category' => '4' , 'description' => 'CHAMARRA CORTA PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '476' , 'id_service_category' => '4' , 'description' => 'CHAMARRA 3/4 PLUMA ' , 'normal_price' => '40' ],
                [ 'id' => '477' , 'id_service_category' => '4' , 'description' => 'CORT TAPICERIA LIENZO' , 'normal_price' => '50' ],
                [ 'id' => '478' , 'id_service_category' => '4' , 'description' => 'CORT, AHULADA LIENZO' , 'normal_price' => '50' ],
                [ 'id' => '479' , 'id_service_category' => '4' , 'description' => 'CORBATA  ' , 'normal_price' => '20' ],
                [ 'id' => '480' , 'id_service_category' => '4' , 'description' => 'CORBATA DE SEDA/LINO' , 'normal_price' => '20' ],
                [ 'id' => '481' , 'id_service_category' => '4' , 'description' => 'CHALECO SENCILLO  ' , 'normal_price' => '20' ],
                [ 'id' => '482' , 'id_service_category' => '4' , 'description' => 'CHALECO GRUESO' , 'normal_price' => '33' ],
                [ 'id' => '483' , 'id_service_category' => '4' , 'description' => 'CHALECO DE PLUMA ' , 'normal_price' => '33' ],
                [ 'id' => '484' , 'id_service_category' => '4' , 'description' => 'CHALECO TEÑIDO' , 'normal_price' => '0' ],
                [ 'id' => '485' , 'id_service_category' => '4' , 'description' => 'PANTS, JUEGO DE 2 PZAS ' , 'normal_price' => '39' ],
                [ 'id' => '486' , 'id_service_category' => '4' , 'description' => 'PLAYERAS DEPORTIVAS  ' , 'normal_price' => '20' ],
                [ 'id' => '487' , 'id_service_category' => '4' , 'description' => 'PANTS, 3 PIEZAS' , 'normal_price' => '40' ],
                [ 'id' => '488' , 'id_service_category' => '4' , 'description' => 'PAR DE TENIS' , 'normal_price' => '25' ],
                [ 'id' => '489' , 'id_service_category' => '4' , 'description' => 'EDREDÓN INDIVIDUAL  ' , 'normal_price' => '50' ],
                [ 'id' => '490' , 'id_service_category' => '4' , 'description' => 'EDREDÓN MATRIMONIAL  ' , 'normal_price' => '50' ],
                [ 'id' => '491' , 'id_service_category' => '4' , 'description' => 'EDREDÓN QUEEN SIZE ' , 'normal_price' => '60' ],
                [ 'id' => '492' , 'id_service_category' => '4' , 'description' => 'EDREDÓN KING SIZE ' , 'normal_price' => '60' ],
                [ 'id' => '493' , 'id_service_category' => '4' , 'description' => 'FALDA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '494' , 'id_service_category' => '4' , 'description' => 'FALDA RECTA LARGA ' , 'normal_price' => '20' ],
                [ 'id' => '495' , 'id_service_category' => '4' , 'description' => 'FALDA RECTA EXTRA LARGA' , 'normal_price' => '20' ],
                [ 'id' => '496' , 'id_service_category' => '4' , 'description' => 'FALDA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '497' , 'id_service_category' => '4' , 'description' => 'FALDA-PANTALON  ' , 'normal_price' => '20' ],
                [ 'id' => '498' , 'id_service_category' => '4' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM LARGA' , 'normal_price' => '33' ],
                [ 'id' => '499' , 'id_service_category' => '4' , 'description' => 'FALDA TABLEADA DE 5 O MAS CM. ' , 'normal_price' => '33' ],
                [ 'id' => '500' , 'id_service_category' => '4' , 'description' => 'FALDA TABLEADA LINO/SEDA ' , 'normal_price' => '33' ],
                [ 'id' => '501' , 'id_service_category' => '4' , 'description' => 'FILIPINA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '502' , 'id_service_category' => '4' , 'description' => 'FILIPINA CON ALMIDÓN ' , 'normal_price' => '21' ],
                [ 'id' => '503' , 'id_service_category' => '4' , 'description' => 'GABARDINA NORMAL  ' , 'normal_price' => '33' ],
                [ 'id' => '504' , 'id_service_category' => '4' , 'description' => 'GABARDINA CON BORREGA ' , 'normal_price' => '56' ],
                [ 'id' => '505' , 'id_service_category' => '4' , 'description' => 'GABARDINA EXTRA LARGA ' , 'normal_price' => '56' ],
                [ 'id' => '506' , 'id_service_category' => '4' , 'description' => 'GUAYABERA  ' , 'normal_price' => '20' ],
                [ 'id' => '507' , 'id_service_category' => '4' , 'description' => 'FUNDAS DE SILLAS ' , 'normal_price' => '50' ],
                [ 'id' => '508' , 'id_service_category' => '4' , 'description' => 'MANTEL SENCILLO RECTANGULAR' , 'normal_price' => '0' ],
                [ 'id' => '509' , 'id_service_category' => '4' , 'description' => 'BUFANDA  ' , 'normal_price' => '20' ],
                [ 'id' => '510' , 'id_service_category' => '4' , 'description' => 'ROPÓN DE BAUTIZO ' , 'normal_price' => '56' ],
                [ 'id' => '511' , 'id_service_category' => '4' , 'description' => 'TENIS' , 'normal_price' => '0' ],
                [ 'id' => '512' , 'id_service_category' => '4' , 'description' => 'MALETAS LAVADO AL VAPOR' , 'normal_price' => '0' ],
                [ 'id' => '513' , 'id_service_category' => '4' , 'description' => 'ZALEA DE BORREGO' , 'normal_price' => '0' ],
                [ 'id' => '514' , 'id_service_category' => '4' , 'description' => 'MALETA DE MANO 30 X 50 CM' , 'normal_price' => '0' ],
                [ 'id' => '515' , 'id_service_category' => '4' , 'description' => 'TRAJE DE BAÑO' , 'normal_price' => '0' ],
                [ 'id' => '516' , 'id_service_category' => '4' , 'description' => 'FUNDA GRANDE COJIN' , 'normal_price' => '0' ],
                [ 'id' => '517' , 'id_service_category' => '4' , 'description' => 'TEÑIDO TAPETE BAÑO ' , 'normal_price' => '0' ],
                [ 'id' => '518' , 'id_service_category' => '4' , 'description' => 'TAPETE DE BAÑO CHICO' , 'normal_price' => '0' ],
                [ 'id' => '519' , 'id_service_category' => '4' , 'description' => 'FUNDA CHICA DE COJIN' , 'normal_price' => '0' ],
                [ 'id' => '520' , 'id_service_category' => '4' , 'description' => 'BANDERA  ' , 'normal_price' => '33' ],
                [ 'id' => '521' , 'id_service_category' => '4' , 'description' => 'CAPA SACERDOTAL SOTANA' , 'normal_price' => '0' ],
                [ 'id' => '522' , 'id_service_category' => '4' , 'description' => 'PERUANAS  ' , 'normal_price' => '33' ],
                [ 'id' => '523' , 'id_service_category' => '4' , 'description' => 'GORRA  ' , 'normal_price' => '20' ],
                [ 'id' => '524' , 'id_service_category' => '4' , 'description' => 'MASCADA' , 'normal_price' => '20' ],
                [ 'id' => '525' , 'id_service_category' => '4' , 'description' => 'MASCADA LINO/SEDA' , 'normal_price' => '20' ],
                [ 'id' => '526' , 'id_service_category' => '4' , 'description' => 'OTROS' , 'normal_price' => '20' ],
                [ 'id' => '527' , 'id_service_category' => '4' , 'description' => 'CAPA/CHALINA' , 'normal_price' => '33' ],
                [ 'id' => '528' , 'id_service_category' => '4' , 'description' => 'PASHMINA' , 'normal_price' => '20' ],
                [ 'id' => '529' , 'id_service_category' => '4' , 'description' => 'OVEROL SENCILLO  ' , 'normal_price' => '40' ],
                [ 'id' => '530' , 'id_service_category' => '4' , 'description' => 'OVEROL DE NIÑO' , 'normal_price' => '40' ],
                [ 'id' => '531' , 'id_service_category' => '4' , 'description' => 'OVEROL DE TRABAJO/MECÁNICO' , 'normal_price' => '40' ],
                [ 'id' => '532' , 'id_service_category' => '4' , 'description' => 'PANTALÓN CABALLERO' , 'normal_price' => '25' ],
                [ 'id' => '533' , 'id_service_category' => '4' , 'description' => 'PANTALÓN DAMA' , 'normal_price' => '20' ],
                [ 'id' => '534' , 'id_service_category' => '4' , 'description' => 'PANTALÓN LINO/SEDA' , 'normal_price' => '30' ],
                [ 'id' => '535' , 'id_service_category' => '4' , 'description' => 'PANTALON TEÑIDO' , 'normal_price' => '150' ],
                [ 'id' => '536' , 'id_service_category' => '4' , 'description' => 'MUÑECO DE PELUCHE CHICO' , 'normal_price' => '18' ],
                [ 'id' => '537' , 'id_service_category' => '4' , 'description' => 'MUÑECO DE PELUCHE MEDIANO' , 'normal_price' => '23' ],
                [ 'id' => '538' , 'id_service_category' => '4' , 'description' => 'MUÑECO DE PELUCHE GRANDE' , 'normal_price' => '28' ],
                [ 'id' => '539' , 'id_service_category' => '4' , 'description' => 'PLAYERA SENCILLA  ' , 'normal_price' => '20' ],
                [ 'id' => '540' , 'id_service_category' => '4' , 'description' => 'PALATZO  ' , 'normal_price' => '30' ],
                [ 'id' => '541' , 'id_service_category' => '4' , 'description' => 'SACO CABALLERO' , 'normal_price' => '20' ],
                [ 'id' => '542' , 'id_service_category' => '4' , 'description' => 'SACO DAMA' , 'normal_price' => '20' ],
                [ 'id' => '543' , 'id_service_category' => '4' , 'description' => 'SACO DE LINO/SEDA ' , 'normal_price' => '20' ],
                [ 'id' => '544' , 'id_service_category' => '4' , 'description' => 'SACO CON ADORNOS ' , 'normal_price' => '33' ],
                [ 'id' => '545' , 'id_service_category' => '4' , 'description' => 'SACO DE NIÑO ' , 'normal_price' => '20' ],
                [ 'id' => '546' , 'id_service_category' => '4' , 'description' => 'SACO TEÑIDO' , 'normal_price' => '0' ],
                [ 'id' => '547' , 'id_service_category' => '4' , 'description' => 'SUDADERA  ' , 'normal_price' => '20' ],
                [ 'id' => '548' , 'id_service_category' => '4' , 'description' => 'TEÑIDO SUDADERA' , 'normal_price' => '0' ],
                [ 'id' => '549' , 'id_service_category' => '4' , 'description' => 'SWEATER SENCILLO  ' , 'normal_price' => '20' ],
                [ 'id' => '550' , 'id_service_category' => '4' , 'description' => 'SWEATER 3/4 DE LARGO' , 'normal_price' => '20' ],
                [ 'id' => '551' , 'id_service_category' => '4' , 'description' => 'SWEATER GRUESO' , 'normal_price' => '33' ],
                [ 'id' => '552' , 'id_service_category' => '4' , 'description' => 'SWEATER DE NIÑO' , 'normal_price' => '20' ],
                [ 'id' => '553' , 'id_service_category' => '4' , 'description' => 'SWEATER ANGORA' , 'normal_price' => '56' ],
                [ 'id' => '554' , 'id_service_category' => '4' , 'description' => 'SWEATER MANGAS DE PIEL/GAMUZA' , 'normal_price' => '56' ],
                [ 'id' => '555' , 'id_service_category' => '4' , 'description' => 'SWEATER FRENTE DE PIEL/GAMUZA' , 'normal_price' => '56' ],
                [ 'id' => '556' , 'id_service_category' => '4' , 'description' => 'TEÑIDO SWETER SENCILLO' , 'normal_price' => '0' ],
                [ 'id' => '557' , 'id_service_category' => '4' , 'description' => 'TRAJE 2 PIEZAS ' , 'normal_price' => '40' ],
                [ 'id' => '558' , 'id_service_category' => '4' , 'description' => 'TRAJE 2 PZAS LINO/SEDA' , 'normal_price' => '56' ],
                [ 'id' => '559' , 'id_service_category' => '4' , 'description' => 'TRAJE 3 PIEZAS ' , 'normal_price' => '56' ],
                [ 'id' => '560' , 'id_service_category' => '4' , 'description' => 'TRAJE 3PZ LINO/SEDA ' , 'normal_price' => '75' ],
                [ 'id' => '561' , 'id_service_category' => '4' , 'description' => 'TRAJE DE NIÑO 2 PZAS ' , 'normal_price' => '40' ],
                [ 'id' => '562' , 'id_service_category' => '4' , 'description' => 'TRAJE DE NIÑO 3 PZAS ' , 'normal_price' => '56' ],
                [ 'id' => '563' , 'id_service_category' => '4' , 'description' => 'SMOKING 2 PIEZAS ' , 'normal_price' => '40' ],
                [ 'id' => '564' , 'id_service_category' => '4' , 'description' => 'SMOKING 3 PIEZAS ' , 'normal_price' => '56' ],
                [ 'id' => '565' , 'id_service_category' => '4' , 'description' => 'VESTIDO SENCILLO  ' , 'normal_price' => '33' ],
                [ 'id' => '566' , 'id_service_category' => '4' , 'description' => 'VESTIDO XV AÑOS ' , 'normal_price' => '75' ],
                [ 'id' => '567' , 'id_service_category' => '4' , 'description' => 'VESTIDO XV AÑOS PEDRERIA' , 'normal_price' => '75' ],
                [ 'id' => '568' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE NOVIA ' , 'normal_price' => '75' ],
                [ 'id' => '569' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE NOVIA CON PEDRERIA ' , 'normal_price' => '100' ],
                [ 'id' => '570' , 'id_service_category' => '4' , 'description' => 'VESTIDO TEÑIDO' , 'normal_price' => '56' ],
                [ 'id' => '571' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE COKTAIL C/PEDRERIA' , 'normal_price' => '0' ],
                [ 'id' => '572' , 'id_service_category' => '4' , 'description' => 'VESTIDO EXTRA LARGO ' , 'normal_price' => '56' ],
                [ 'id' => '573' , 'id_service_category' => '4' , 'description' => 'VESTIDO LINO/SEDA  ' , 'normal_price' => '75' ],
                [ 'id' => '574' , 'id_service_category' => '4' , 'description' => 'VESTIDO LINO/SEDA EXT LARGO' , 'normal_price' => '75' ],
                [ 'id' => '575' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE NIÑA ' , 'normal_price' => '33' ],
                [ 'id' => '576' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE NIÑA FIESTA' , 'normal_price' => '56' ],
                [ 'id' => '577' , 'id_service_category' => '4' , 'description' => 'VESTIDO PRIMERA COMUNION' , 'normal_price' => '75' ],
                [ 'id' => '578' , 'id_service_category' => '4' , 'description' => 'VESTIDO DE COCKTAIL' , 'normal_price' => '33' ],
                [ 'id' => '579' , 'id_service_category' => '4' , 'description' => 'VESTIDO PEDR O ADORNOS' , 'normal_price' => '75' ],
                [ 'id' => '580' , 'id_service_category' => '4' , 'description' => 'BANDERA CHICA' , 'normal_price' => '25' ],
                [ 'id' => '581' , 'id_service_category' => '4' , 'description' => 'CORTINA LARGA' , 'normal_price' => '45' ],
                [ 'id' => '582' , 'id_service_category' => '4' , 'description' => 'CORTINA DE BALCON' , 'normal_price' => '30' ],
                [ 'id' => '583' , 'id_service_category' => '4' , 'description' => 'CAMINO DE MESA EXLA' , 'normal_price' => '75' ],
                [ 'id' => '584' , 'id_service_category' => '4' , 'description' => 'DUVET' , 'normal_price' => '40' ],
                [ 'id' => '585' , 'id_service_category' => '5' , 'description' => 'BATAS LAV+PLAN 1/2 DOCENA' , 'normal_price' => '120' ],
                [ 'id' => '586' , 'id_service_category' => '5' , 'description' => 'BATAS LAV+PLAN DOCENA ' , 'normal_price' => '225' ],
                [ 'id' => '587' , 'id_service_category' => '5' , 'description' => 'CAMISA 1/2 DOCENA ALMIDON' , 'normal_price' => '110' ],
                [ 'id' => '588' , 'id_service_category' => '5' , 'description' => 'CAMISA DOCENA ALMIDON' , 'normal_price' => '206' ],
                [ 'id' => '589' , 'id_service_category' => '5' , 'description' => 'CAMISA EXTRA a partir de 1/2 docena' , 'normal_price' => '13' ],
                [ 'id' => '590' , 'id_service_category' => '5' , 'description' => 'CAMISA 1/2 DOCENA' , 'normal_price' => '75' ],
                [ 'id' => '591' , 'id_service_category' => '5' , 'description' => 'CAMISA DOCENA' , 'normal_price' => '150' ],
                [ 'id' => '592' , 'id_service_category' => '5' , 'description' => 'EMPAQUE AL VACÍO' , 'normal_price' => '700' ],
                [ 'id' => '593' , 'id_service_category' => '5' , 'description' => 'CAMISAS LAV+PLAN 1/2 DOCENA' , 'normal_price' => '95' ],
                [ 'id' => '594' , 'id_service_category' => '5' , 'description' => 'CAMISAS LAV+PLAN DOCENA' , 'normal_price' => '190' ],
                [ 'id' => '595' , 'id_service_category' => '5' , 'description' => 'FILIPINA DOCENA' , 'normal_price' => '150' ],
                [ 'id' => '596' , 'id_service_category' => '5' , 'description' => 'FILIPINA 1/2 DOCENA' , 'normal_price' => '80' ],
                [ 'id' => '597' , 'id_service_category' => '5' , 'description' => 'CAMISA LAV Y PLAN' , 'normal_price' => '29' ],
                [ 'id' => '598' , 'id_service_category' => '5' , 'description' => 'PANTALÓN LAV Y PLAN' , 'normal_price' => '29' ],
                [ 'id' => '599' , 'id_service_category' => '5' , 'description' => 'FALDA LAV Y PLAN' , 'normal_price' => '29' ],
                [ 'id' => '600' , 'id_service_category' => '5' , 'description' => 'PLAYERA LAV Y PLAN' , 'normal_price' => '29' ],
                [ 'id' => '601' , 'id_service_category' => '5' , 'description' => 'BLUSA LAV Y PLAN' , 'normal_price' => '29' ],
                [ 'id' => '602' , 'id_service_category' => '5' , 'description' => 'CAMISA ALMIDON' , 'normal_price' => '35' ],
                [ 'id' => '603' , 'id_service_category' => '6' , 'description' => 'LAVADO Y PLANCHADO SERVILLETAS' , 'normal_price' => '5.8' ],
            )
        );
    }
}
